apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dohyunkim
  namespace: software
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
